image: node:latest

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

services:
  - name: mongo:latest
    alias: database

stages:
  # - Test
  - Build

# Test:
#   stage: Test
#   image: node:latest
#   before_script:
#     - "npm config set loglevel warn"
#     - "cd keys"
#     - "ssh-keygen -t rsa -b 4096 -m PEM -f private.key -q -N ''"
#     - "openssl rsa -in private.key -pubout -outform PEM -out public.key"
#     - "cd .."
#     - "npm install"
#   script:
#     - npm run test
#   cache:
#     paths:
#       - node_modules/

Staging Build:
  stage: Build
  image: docker:stable
  services:
    - docker:18-dind
  before_script:
    - "docker login registry.mira.systems -u ${DOCKER_USER} -p ${DOCKER_PASS}"
  script:
    - "docker build -t registry.mira.systems/farmlab/mqtt-api:staging-latest -t registry.mira.systems/farmlab/mqtt-api:dev-${CI_COMMIT_SHORT_SHA} ."
    - "docker push registry.mira.systems/farmlab/mqtt-api:staging-latest"
    - "docker push registry.mira.systems/farmlab/mqtt-api:dev-${CI_COMMIT_SHORT_SHA}"
  after_script:
    - docker logout registry.mira.systems
  when: manual
  except:
    - master

Production Build:
  stage: Build
  image: docker:stable
  services:
    - docker:18-dind
  before_script:
    - "docker login registry.mira.systems -u ${DOCKER_USER} -p ${DOCKER_PASS}"
  script:
    - "docker build -t registry.mira.systems/farmlab/mqtt-api:latest ."
    - "docker push registry.mira.systems/farmlab/mqtt-api:latest"
  after_script:
    - docker logout registry.mira.systems
  when: manual
  only:
    - master