version: "3.7"

volumes:
  farmlab-db-data:
  farmlab-db-conf:

services:
  api:
    image: registry.mira.systems/farmlab/mqtt-api:latest
    container_name: "farmlab-api"
    restart: unless-stopped
    ports:
      - 1887:1887
      - 8080:8080
    depends_on:
      - database

  database:
    image: mongo
    container_name: "farmlab-db"
    restart: unless-stopped
    volumes:
      - farmlab-db-data:/data/db
      - farmlab-db-conf:/data/configdb
