version: "3.7"

volumes:
  db-data:
  db-conf:

services:
  api:
    image: registry.mira.systems/farmlab/mqtt-api:latest
    container_name: FarmLab-API
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8080:8080
    volumes:
      - ./keys:/app/keys
      - ./config:/app/config

  database:
    image: mongo:latest
    container_name: FarmLab-DB
    restart: unless-stopped
    volumes:
      - db-data:/data/db
      - db-conf:/data/configdb
